/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/7.2/userguide/building_java_projects.html
 */

plugins {
    id("org.jetbrains.kotlin.jvm") // required for Kotlin DSL syntax
}

dependencies {
    val komputingKBase58Version = "0.4"
    implementation("com.github.komputing:KBase58:${komputingKBase58Version}")
}

publishing {
    publications {
        register<MavenPublication>("gpr") {
            groupId = project.rootProject.group.toString()
            artifactId = "providers-api"
            version = project.rootProject.version.toString()
            from(components["java"])
        }
    }
}
