name: Build pipeline
on: [ push ]
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Build with Gradle
        run: ./gradlew build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Publish package
        run: ./gradle publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
